import json
import os


class DecisionAgent:
    """
    Maps trust score to one of three routing decisions.
    Thresholds are loaded from models/trust_thresholds.json if available
    (generated by training/calibrate_thresholds.py), otherwise uses defaults.
    """

    DEFAULT_GENERATE    = 0.80
    DEFAULT_ESCALATION  = 0.50

    def __init__(
        self,
        generate_threshold: float = None,
        escalation_threshold: float = None,
        thresholds_path: str = "models/trust_thresholds.json"
    ):
        # Try loading calibrated thresholds
        if generate_threshold is None and os.path.exists(thresholds_path):
            try:
                with open(thresholds_path) as f:
                    t = json.load(f)
                self.generate_threshold   = t["generate_threshold"]
                self.escalation_threshold = t["escalation_threshold"]
                print(f"[DecisionAgent] Loaded calibrated thresholds: "
                      f"generate={self.generate_threshold}, "
                      f"escalate={self.escalation_threshold}")
            except Exception as e:
                print(f"[DecisionAgent] Could not load thresholds: {e}, using defaults")
                self.generate_threshold   = self.DEFAULT_GENERATE
                self.escalation_threshold = self.DEFAULT_ESCALATION
        else:
            self.generate_threshold   = generate_threshold or self.DEFAULT_GENERATE
            self.escalation_threshold = escalation_threshold or self.DEFAULT_ESCALATION
            print(f"[DecisionAgent] Using thresholds: "
                  f"generate={self.generate_threshold}, "
                  f"escalate={self.escalation_threshold}")

    def decide(self, trust_score: float) -> str:

        if trust_score >= self.generate_threshold:
            return "generate"

        if trust_score >= self.escalation_threshold:
            return "escalate"

        return "insufficient"